name: daq_sensor_dashboard
description: "Sensor selection and real-time display UI."
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  fl_chart: ^0.69.0
  web_socket_channel: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.2
  window_manager: ^0.3.9
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

